add curl and axel support

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,11 +3,15 @@ name: a1to5x
 on:
   workflow_dispatch:
      inputs:
-       zipname:
-         description: 'ROM NAME(No file extension: crDroidAndroid-11.0-20201126-tissot-v7.0)'
+       mode:
+         description: 'Download mode(wget,aria2c,curl,axel)'
+         required: true
+         default: 'aria2c'
+       filename:
+         description: 'ROM NAME'
          required: false
        filelink:
-         description: 'ROM LINK(Downloadable link)'
+         description: 'ROM LINK'
          required: true
 
 jobs:
@@ -22,7 +26,7 @@ jobs:
       - name: Initialization environment
         run: |
           sudo -E apt-get -qq update
-          sudo -E apt-get -qq install git openjdk-8-jdk wget curl rsync aria2 python python3 unzip device-tree-compiler brotli simg2img img2simg
+          sudo -E apt-get -qq install git openjdk-8-jdk wget curl rsync aria2 python python3 unzip device-tree-compiler brotli simg2img img2simg axel
           pip3 install protobuf
           pip install brotli
 
@@ -30,26 +34,54 @@ jobs:
         name: Download
         run: |
           echo "Download"
-          if [[ ! -z "${{ github.event.inputs.filelink }}" ]]; then
-              if [[ ! -z "${{ github.event.inputs.zipname }}" ]]; then
-                  aria2c -x16 -j$(nproc) -o "${{ github.event.inputs.zipname }}" ${{ github.event.inputs.filelink }} || wget ${{ github.event.inputs.filelink }} -O "${{ github.event.inputs.zipname }}"
-                  echo "::set-output name=zipname::${{ github.event.inputs.zipname }}"
-              else
-                  aria2c -x16 -j$(nproc) ${{ github.event.inputs.filelink }} || wget ${{ github.event.inputs.filelink }}
-                  NAME="$(ls -lS *.zip | head -1 | awk '{print $9}')"
-                  zipname=${NAME%.*}
-                  echo "::set-output name=zipname::$zipname"
+          if [[ ! -z "${{ github.event.inputs.filename }}" ]]; then              
+              if [[ "${{ github.event.inputs.mode }}" == 'wget' ]]; then
+                  wget ${{ github.event.inputs.filelink }} -O "${{ github.event.inputs.filename }}.zip"
+                  echo "::set-output name=filename::${{ github.event.inputs.filename }}"
+              elif [[ "${{ github.event.inputs.mode }}" == 'aria2c' ]]; then
+                  aria2c -x16 -j$(nproc) ${{ github.event.inputs.filelink }} -o "${{ github.event.inputs.filename }}.zip"
+                  echo "::set-output name=filename::${{ github.event.inputs.filename }}"                 
+              elif [[ "${{ github.event.inputs.mode }}" == 'curl' ]]; then
+                  curl -L ${{ github.event.inputs.filelink }} -o "${{ github.event.inputs.filename }}.zip"
+                  echo "::set-output name=filename::${{ github.event.inputs.filename }}"
+              elif [[ "${{ github.event.inputs.mode }}" == 'axel' ]]; then
+                  axel -n 16 ${{ github.event.inputs.filelink }} -o "${{ github.event.inputs.filename }}.zip"
+                  echo "::set-output name=filename::${{ github.event.inputs.filename }}"
               fi
+              
           else
-              echo "The link does not exist"
-              exit 1
+              if [[ "${{ github.event.inputs.mode }}" == 'wget' ]]; then
+                  wget --content-disposition -c ${{ github.event.inputs.filelink }}
+              elif [[ "${{ github.event.inputs.mode }}" == 'aria2c' ]]; then
+                  aria2c -x16 -j$(nproc) ${{ github.event.inputs.filelink }}             
+              elif [[ "${{ github.event.inputs.mode }}" == 'curl' ]]; then
+                  curl -OL ${{ github.event.inputs.filelink }}
+              elif [[ "${{ github.event.inputs.mode }}" == 'axel' ]]; then
+                  axel -n 16 ${{ github.event.inputs.filelink }}
+              fi
+              NAME="$(ls -lS *.zip | head -1 | awk '{print $9}')"
+              if [ ! -z "$NAME" ]; then
+                  filename=${NAME%.*}
+              else
+                  tmp="$(find . -maxdepth 1 -type f -size +500M)"
+                  if [ ! -z "$tmp" ]; then
+                      ls -al
+                      echo "Rename"
+                      filename=$(echo $tmp | sed 's#./##')
+                      mv $filename ${filename}.zip
+                  else
+                      echo "Download error"
+                      exit 1
+                  fi
+              fi              
+              echo "::set-output name=filename::$filename"
           fi
           ls -al
 
       - name: Payload Extractor
         run: |
           echo "Payload Dumper"
-          unzip ${{ steps.var.outputs.zipname }}.zip payload.bin
+          unzip ${{ steps.var.outputs.filename }}.zip payload.bin
           python3 update-payload-extractor/extract.py payload.bin --output_dir ./
           ls -al
 
@@ -144,13 +176,13 @@ jobs:
           rm system.new.dat
           ls -al
           cd ..
-          mv template ${{ steps.var.outputs.zipname }}
+          mv template ${{ steps.var.outputs.filename }}
           
 
       - name: Upload to Artifact
         uses: actions/upload-artifact@v2
         with:
-          name: ${{ steps.var.outputs.zipname }}
+          name: ${{ steps.var.outputs.filename }}
           path: |
-            ${{ steps.var.outputs.zipname }}
+            ${{ steps.var.outputs.filename }}
           retention-days: 7
